# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06d64593512f2124cf50ce8708ff927a85dbd8a6f6ec52d0ad37c3c7350ba398515b0ff2cc5fcd2cc046b8c437860eecc41939d5e03a6a3ee457cc5a32612875

test:
  secret_key_base: 02072e7221083de945bdb77ecc571d2b66172380eab8fdffa1215a0754b2656e2aa523bff31097c436c41ae415ed1945759f8fc4a3c3f98952cd3f15fe915444

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
